<!DOCTYPE html>
<html lang="pt-BR">
<head>
   <?php include('includes/sections/section_head.php'); ?>
   <title>Termos e condições | Lojas Deltasul</title>
</head>
<?php include('includes/sections/section_header.php'); ?>
    <body class="home-header">
      <main class="main" id="main">
         <section class="breadcrumb">
            <div class="av-container">
               <div class="av-row">
                  <div class="av-col-xs-24">
                     <div class="bread-crumb">
                        <div class="draft-article" style="margin: 20px 0px">
                        <b style="font-size: 22px;">Termos e condições de compra e venda de produtos</b>
                        <p style="margin: 8px 0px">Deltasul Utilidades - CNPJ 98.102.924/0001-01 - PRESIDENTE CASTELO BRANCO - DISTR. INDUSTRIAL - SANTA CRUZ DO SUL - RS - CEP 96835-666 - doravante denominada simplesmente Deltasul, e, de outro lado, o cliente da Deltasul, qualificado no momento da compra dos produtos Deltasul, doravante denominado simplesmente Cliente.</p>
                        <p style="margin: 8px 0px">Considerando que a Deltasul realiza venda de produtos e serviços nacionais pela internet;</p>
                        <p style="margin: 8px 0px">O presente contrato tem por finalidade estabelecer as condições gerais de uso e compra de produtos e serviços pelo Cliente por meio dos sites Deltasul (www.deltasul.com.br) (“Websites”).</p>
                        <p style="margin: 8px 0px"><b>1.</b> <b>confidencialidade</b></p>
                        <p style="margin: 8px 0px">1.1. É de responsabilidade da Deltasul a preservação da confidencialidade de todos os dados e informações fornecidos pelo Cliente no processo de compra. A segurança do site é auditada diariamente e garantida contra a ação de hackers, por meio do selo "Site Blindado".</p>
                        <p style="margin: 8px 0px">1.2. O Cliente, por sua vez, se compromete a não disponibilizar suas senhas de acesso aos Websites a terceiros, bem como a tomar providências razoáveis para manter suas informações sob sigilo. Caso o Cliente identifique e/ou desconfie que terceiros tiveram acesso às suas senhas, este se compromete a comunicar a Deltasul para que as devidas providências sejam tomadas.</p>
                        <p style="margin: 8px 0px">1.3. Apenas pessoas físicas maiores de 18 (dezoito) anos poderão se cadastrar e utilizar-se dos serviços prestados pela Deltasul. Reservamo-nos o direito de excluir o cadastro e cancelar pedidos de menores de idades, porém valores pagos por serviços já prestados não serão devolvidos no caso da violação desta regra.</p>
                        <p style="margin: 8px 0px">1.4. Ao preencher o cadastro, o Cliente declara que as informações que o identificam são verdadeiras, precisas e completas, bem como se declara ciente de que eventuais falsidades poderão sujeita-lo às responsabilidades criminais e cíveis, de acordo com a legislação brasileira.</p>
                        <p style="margin: 8px 0px">1.5. O Cliente expressamente autoriza que suas informações e dados pessoais sejam compartilhados pela Deltasul nas seguintes hipóteses:</p>
                        <p style="margin: 8px 0px">1.5.1 com as demais empresas integrantes do grupo econômico e autoridades, conforme necessário para o processo de compra e o cumprimento da legislação em vigor;</p>
                        <p style="margin: 8px 0px">1.5.2 com o Agente de Câmbio, na medida em que forem necessárias para que este execute as operações cambiais para a compra realizada via Parceiro Deltasul Mundo, nos termos da legislação vigente;</p>
                        <p style="margin: 8px 0px">1.5.3 com parceiros comerciais, com os quais a Deltasul mantém um relacionamento de colaboração ou parceria, a fim de oferecer soluções financeiras e linha de crédito pré-aprovado.</p>
                        <p style="margin: 8px 0px"><b>2.</b> <b>opiniões, avaliações e perguntas dos clientes cadastrados</b></p>
                        <p style="margin: 8px 0px">2.1. Para melhoria dos serviços e para que os Clientes possam efetuar a melhor escolha de compra, o Cliente poderá postar opiniões, avaliações, comentários e enviar perguntas.</p>
                        <p style="margin: 8px 0px">2.2. Ao submeter qualquer conteúdo, o Cliente declara e garante que: i) é autor exclusivo e proprietário dos direitos relativos aos conteúdos postados; ii) o conteúdo é seguro e exato; iii) o uso do conteúdo fornecido não viola as políticas da Deltasul e não causará danos a qualquer pessoa ou entidade.</p>
                        <p style="margin: 8px 0px">2.3. O conteúdo postado pelo Cliente não poderá ser falso, impreciso, ilusório, difamatório, acusatório, odioso, racialmente ou religiosamente preconceituoso ou ofensivo, ameaçador, prejudicial a terceiros, ter cunho político, infringir a legislação, violar direitos autorais ou de propriedade intelectual, fazer referência a outros websites, endereços, endereços de e-mail, informações de contato ou números de telefone, e não poderá conter qualquer vírus de computador, worms ou outros arquivos ou programas potencialmente danosos.</p>
                        <p style="margin: 8px 0px">2.4. A Deltasul não assume qualquer responsabilidade quanto ao conteúdo fornecido e postado por seus Clientes. No entanto, é faculdade da Deltasul a não publicação ou exclusão de qualquer opinião, avaliação, dados, perguntas ou qualquer outro conteúdo que sejam caracterizados como contrários à Lei, aos princípios constitucionais, morais e éticos, bem como os que violem os termos e condições da Deltasul, sem que haja direito à devolução de qualquer valor eventualmente pago pelo Cliente. </p>
                        <p style="margin: 8px 0px">2.5. Autores de comentários ofensivos ou em desacordo com as diretrizes da Companhia poderão ser responsabilizados civil e criminalmente, por conteúdos publicados que violem a Lei e ou produzam lesão a direito de terceiros e ou da Deltasul. O Cliente concorda em indenizar a Companhia por todos os danos, perdas, prejuízos e despesas, de qualquer tipo e natureza, decorrentes ou relacionadas a demandas provenientes do conteúdo que o Cliente fornecer.</p>
                        <p style="margin: 8px 0px">2.6. Para qualquer conteúdo que enviar, o Cliente concede à Deltasul licença e direitos perpétuos, irrevogáveis e livres de royalties para reproduzir, usar, copiar, modificar, excluir em sua totalidade, adaptar, publicar, traduzir, criar trabalhos derivados e/ou vender e/ou distribuir tal conteúdo e/ou incorporá-lo a qualquer forma, meio ou tecnologia em todo o mundo sem remuneração ao Cliente. Todo o conteúdo que o Cliente enviar pode ser usado segundo os critérios da Deltasul.</p>
                        <p style="margin: 8px 0px">2.7. Ao submeter qualquer conteúdo, o Cliente concorda que Deltasul e seus provedores de serviço podem usar seu endereço de e-mail cadastrado para entrar em contato com você a respeito da situação de seu perfil e por outros motivos administrativos.</p>
                        <p style="margin: 8px 0px"><b>3.</b> <b>serviço de atendimento ao cliente (sac)</b></p>
                        <p style="margin: 8px 0px">3.1. O Cliente dispõe desse serviço para sanar suas dúvidas, solucionar eventuais solicitações ou reclamações a respeito do seu pedido ou de qualquer conteúdo disponibilizado nos Websites. O SAC poderá ser acionado por meio de telefone, formulário do Website ou envio de e-mail para atendimento.acom@Deltasul.com, todos disponibilizados em nossa "Central de Atendimento" (SAC).</p>
                        <p style="margin: 8px 0px">3.2. Caso o contato com o SAC se refira aos Produtos vendidos e entregues pelos Parceiros do Marketplace e/ou Parceiros da Deltasul Mundo, tais Parceiros serão responsáveis por sanar as dúvidas, eventuais solicitações ou reclamações a respeito do seu pedido ou de qualquer conteúdo disponibilizado por ele nos Websites.</p>
                        <p style="margin: 8px 0px"><b>4.</b> <b>política de entrega</b></p>
                        <p style="margin: 8px 0px">4.1. O prazo para entrega dos Produtos é informado durante o procedimento de compra, sendo contabilizado em dias úteis. As entregas dos Produtos são realizadas de segunda a sexta-feira, das 8h às 22h. Excepcionalmente, algumas entregas de Produtos podem ocorrer aos sábados, domingos e feriados.</p>
                        <p style="margin: 8px 0px">4.2. A conferência da adequação das dimensões do Produto é de exclusiva responsabilidade do Cliente, que deverá se assegurar de que estão de acordo com os limites espaciais dos elevadores, portas e corredores do local da entrega. <b>Não será realizada a montagem ou desmontagem do Produto, transporte pela escada e/ou portas e janelas, ou içamento das mercadorias.</b></p>
                        <p style="margin: 8px 0px">4.3. Serão realizadas até três tentativas de entrega no local informado pelo Cliente, em dias alternados, com intervalo de até 48h entre uma entrega e outra. É indispensável que, no endereço informado, haja uma pessoa autorizada pelo comprador, maior de 18 anos e responsável, portando documento de identificação para receber a mercadoria e assinar o protocolo de entrega. Se houver três tentativas de entrega sem sucesso, o Cliente entende e aceita que o pedido retornará para o Centro de Distribuição da Deltasul.</p>
                        <p style="margin: 8px 0px">4.4. <b>Após a finalização do pedido não é possível alterar a forma de pagamento e/ou o endereço de entrega, solicitar adiantamento ou, ainda, prioridade da entrega.</b></p>
                        <p style="margin: 8px 0px">4.5. O prazo de entrega informado durante o procedimento de compra do Produto leva em consideração o estoque, a região, o processo de emissão da nota fiscal e o tempo de preparo do Produto. A cada atualização no status de entrega do pedido, o sistema da Deltasul envia, automaticamente, e-mails de alerta para o Cliente.</p>
                        <p style="margin: 8px 0px">4.6. O valor do frete da entrega é calculado com base no local de entrega, peso e dimensões do Produto.</p>
                        <p style="margin: 8px 0px">4.7. A Deltasul não autoriza a transportadora a:</p>
                        <p style="margin: 8px 0px">· Entrar no domicílio onde será entregue o Produto;</p>
                        <p style="margin: 8px 0px">· Entregar o Produto por meios alternativos (exemplo: içar Produto pela janela);</p>
                        <p style="margin: 8px 0px">· Realizar instalação ou manutenção de Produtos;</p>
                        <p style="margin: 8px 0px">· Abrir a embalagem do Produto;</p>
                        <p style="margin: 8px 0px">· Realizar entrega em endereço diferente do que consta na nota fiscal e/ou invoice, que é o documento enviado nas vendas de produtos e/ou serviços internacionais;</p>
                        <p style="margin: 8px 0px">· Entregar o Produto para pessoa com menos de 18 anos e/ou sem documento de identificação.</p>
                        <p style="margin: 8px 0px">4.8. <b>A Deltasul</b> <b>não se responsabiliza pela retenção de mercadorias na Secretaria da Fazenda - SEFAZ quando esta se dever exclusivamente a pendências do cliente, sendo, portanto, necessário o comparecimento deste no posto fiscal para que a mercadoria seja devidamente liberada, tendo em vista que nestes casos as informações referentes a liberações e pagamentos só são passadas aos interessados.</b></p>
                        <p style="margin: 8px 0px">4.9. As regras dispostas nos itens 4.1 ao 4.8 também são aplicáveis aos Produtos vendidos e entregues pelos Parceiros do Marketplace e da Deltasul Mundo, exceto naquilo que a política de entrega do Parceiro dispuser expressamente de forma contrária.</p>
                        <p style="margin: 8px 0px">4.10. Para todos os fins e efeitos, o cliente da Deltasul Mundo será considerado importador do Produto e único responsável pela compra internacional realizada, tendo em vista que a Deltasul apenas disponibiliza a sua plataforma para intermediação e realização do negócio.</p>
                        <p style="margin: 8px 0px">4.11. Além disso, o Cliente entende que o Parceiro Deltasul Mundo é integralmente responsável pelos Produtos disponibilizados em seus Websites e suas respectivas características, bem como por providenciar o envio de tais Produtos em tempo hábil e conformidade com as leis brasileiras de comércio internacional, além de outras que se apliquem.</p>
                        <p style="margin: 8px 0px"><b>5.</b> <b>direito de arrependimento</b></p>
                        <p style="margin: 8px 0px">5.1. Ao Cliente será facultado o exercício do direito de arrependimento da compra, com a finalidade de devolução do Produto, hipótese na qual deverão ser observadas as seguintes condições: </p>
                        <p style="margin: 8px 0px">· O prazo de desistência da compra do Produto é de até 7 (sete) dias corridos, a contar da data do recebimento; </p>
                        <ul class="sc-bdVaJa gBMKZQ ListUlUI-sc-13efbnv-0 demFGM">
                            <li data-key="0" class="ListItem-sc-13efbnv-2 fzoHck"><span class="TextUI-sc-12tokcy-0 kmgcjh">o prazo de desistência da compra de produtos      da categoria Moda é de até 30 (trinta) dias corridos, a contar da data do      recebimento do Produto;</b></li>
                        </ul>
                        <p style="margin: 8px 0px">· Em caso de desistência da compra, o Produto deverá ser devolvido à Deltasul na embalagem original ou similar, acompanhado da nota fiscal (ou invoice), do manual e de todos os seus acessórios.</p>
                        <p style="margin: 8px 0px">5.2. O Cliente deverá solicitar a devolução por meio do Serviço de Atendimento ao Cliente (SAC) ou diretamente no Painel de Controle, no tópico "cancelar pedido". As despesas decorrentes de coleta ou postagem do Produto serão custeadas pela Deltasul ou pelo Parceiro.</p>
                        <p style="margin: 8px 0px">5.3. Após a chegada do Produto ao Centro de Distribuição, a Deltasul verificará se as condições supracitadas foram atendidas. Em caso afirmativo, providenciará a restituição no valor total da compra.</p>
                        <p style="margin: 8px 0px">5.4. Em compras com cartão de crédito, a administradora do cartão será notificada e o estorno ocorrerá na fatura seguinte ou na posterior, de uma só vez, seja qual for o número de parcelas utilizado na compra. O prazo de ressarcimento e, ainda, a cobrança das parcelas remanescentes após o estorno integral do valor do Produto no cartão de crédito do Cliente realizado pela Deltasul, é de exclusiva responsabilidade da administradora do cartão. Na hipótese de cobrança de parcelas futuras pela administradora do cartão, o Cliente não será onerado, uma vez que a Deltasul, conforme mencionado acima, realiza o estorno do valor integral do Produto em uma única vez, sendo o crédito referente ao estorno concedido integralmente pela administradora do cartão na fatura de cobrança subsequente ao mês do cancelamento.</p>
                        <p style="margin: 8px 0px">5.5. Em compras pagas com boleto bancário ou débito em conta, a restituição será efetuada por meio de depósito bancário, em até 10 (dez) dias úteis, somente na conta corrente do(a) comprador(a), que deve ser individual. É necessário que o CPF do titular da conta corrente seja o mesmo que consta no pedido (CPF do Cliente). Caso o(a) comprador(a) não tenha uma conta corrente que atenda às condições citadas, será enviada, no mesmo prazo, uma Ordem de Pagamento em nome do titular da compra. Ela poderá ser resgatada em qualquer agência do Banco Itaú, mediante apresentação de documento de identidade e CPF.</p>
                        <p style="margin: 8px 0px">5.6. Em compras com vale ou com qualquer outra forma de pagamento é possível receber um vale no mesmo valor da compra. Em caso de cancelamento do vale, o reembolso será realizado na mesma forma de pagamento escolhida no processo de compra.</p>
                        <p style="margin: 8px 0px">5.7. A Deltasul isenta-se da obrigação de cancelar qualquer Produto que não preencha os requisitos elencados neste dispositivo.</p>
                        <p style="margin: 8px 0px"><b>6.</b> <b>política de trocas e devoluções</b></p>
                        <p style="margin: 8px 0px">6.1. Todas as ocorrências que envolvam troca ou devolução serão atendidas conforme o previsto no Código de Defesa do Consumidor.</p>
                        <p style="margin: 8px 0px">6.2. O Cliente deverá solicitar a troca ou devolução por meio do Serviço de Atendimento ao Cliente (SAC) ou diretamente no Painel de Controle, no tópico "cancelar pedido". As despesas decorrentes de coleta ou postagem do Produto serão custeadas pela Deltasul ou pelo Parceiro.</p>
                        <p style="margin: 8px 0px">6.3. O Produto deverá ser devolvido à Deltasul na embalagem original ou similar, acompanhado da nota fiscal (ou invoice), do manual e de todos os seus acessórios.</p>
                        <p style="margin: 8px 0px">6.4. Após a chegada do Produto ao Centro de Distribuição, a Deltasul verificará se as condições supracitadas foram atendidas. Em caso afirmativo, providenciará a restituição ou troca do Produto de acordo com a solicitação feita pelo Cliente.</p>
                        <p style="margin: 8px 0px">6.5. Troca de produtos da categoria Moda: O cliente poderá trocar o tamanho ou a cor dos itens de Moda, ou trocá-los por qualquer produto disponível à venda no site, independentemente da categoria, marca ou coleção. A troca fica condicionada à disponibilidade do Produto em estoque. O prazo para solicitar a troca dos itens de moda, mesmo nos casos em que não há vício ou defeito no produto, é de 30 dias corridos para produtos vendidos e entregues por Deltasul e de 7 dias corridos para produtos vendidos por lojas parceiras, contados a partir da data de entrega.</p>
                        <p style="margin: 8px 0px">6.6. A Deltasul isenta-se da obrigação de atender às solicitações de troca ou devolução de qualquer Produto devolvido sem que o setor de Atendimento ao Cliente seja comunicado, ou nos casos de solicitação direta no Painel de Controle, fora do prazo ou na ausência de itens/acessórios que o acompanham.</p>
                        <p style="margin: 8px 0px">6.7. <b>Nos casos de ofertas de Produtos vendidos na Deltasul Mundo, por se tratar de uma relação de importação, os serviços relacionados à assistência técnica, garantia ou política de troca de Produtos podem variar de acordo com o respectivo Parceiro Deltasul Mundo.</b></p>
                        <p style="margin: 8px 0px"><b>7.</b> <b>formas de pagamento aceitas</b></p>
                        <p style="margin: 8px 0px">7.1. Pagamento à vista: Ame Digital; Boleto bancário; Débito em conta; Cartão de crédito;</p>
                        <p style="margin: 8px 0px">7.2. Pagamento parcelado: Ame Digital/Cartão de crédito.</p>
                        <p style="margin: 8px 0px">7.3. Para pagamentos com cartão de crédito, o pedido estará sujeito à aprovação da administradora do cartão. As informações contidas no cadastro são passíveis de confirmação, que poderá ser solicitada pela Deltasul por e-mail.</p>
                        <p style="margin: 8px 0px">7.4. O Cliente poderá adquirir o vale após o cancelamento de um pedido feito no site Deltasul, ou também ao ser presenteado. O vale terá seu valor convertido em compras no próprio Website.</p>
                        <p style="margin: 8px 0px">7.5. Para realizar o pagamento com vale, é necessário que o cliente realize o desbloqueio do vale no “painel de controle” antes da sua utilização</p>
                        <p style="margin: 8px 0px">7.6. O Cliente aceita e reconhece que o vale expira um ano após a data de recebimento e é identificado pelo CPF do comprador, o que impede o uso por terceiros.</p>
                        <p style="margin: 8px 0px">7.7. <b>Se o valor do vale for menor que o da compra, o Cliente poderá pagar a diferença somente com cartão de crédito</b>. Se o valor do vale for maior que o da compra, o Cliente poderá utilizar a diferença em outras compras na Deltasul.</p>
                        <p style="margin: 8px 0px"><b>8.</b> <b>prazos de entrega e forma de pagamento</b></p>
                        <p style="margin: 8px 0px">8.1.  Compras pagas com cartão de crédito: o prazo para entrega é considerado a partir da checagem de dados cadastrais e da confirmação do pagamento pela administradora do cartão. A confirmação é realizada em até dois dias corridos, sendo que em caso de divergência cadastral, a Deltasul entrará em contato com o comprador.</p>
                        <p style="margin: 8px 0px">8.2. Compras pagas por meio de boleto bancário: o prazo para entrega é considerado a partir da confirmação do pagamento pelo banco. A confirmação é realizada em até três dias úteis, a partir do pagamento.</p>
                        <p style="margin: 8px 0px">8.3. Compras pagas por meio de débito em conta: o prazo para entrega é considerado a partir da confirmação do pagamento pelo banco. A confirmação é realizada em até dois dias corridos.</p>
                        <p style="margin: 8px 0px">8.4. Compras pagas por meio de vale: se o valor do vale for maior ou igual ao valor da compra, o prazo para entrega é considerado a partir da confirmação do pagamento que ocorre em até 72 horas; se o valor do vale for menor que o valor da compra, a diferença somente poderá ser paga por meio de cartão de crédito e o prazo de entrega começa a contar após a aprovação do pagamento pela administradora do cartão.</p>
                        <p style="margin: 8px 0px">8.5. Os preços dos Produtos vendidos na Deltasul Mundo serão publicados em Reais e estão sujeitos a variações cambiais enquanto os Produtos estiverem disponíveis para a venda, motivo pelo qual o valor da oferta dos Produtos poderá ser atualizado constantemente na respectiva página de anúncio, sem prévio aviso. Uma vez concluída corretamente a transação de compra, o valor não será alterado.</p>
                        <p style="margin: 8px 0px"><b>9.</b> <b>mandato</b></p>
                        <p style="margin: 8px 0px">9.1. Nos casos de compras de Produtos na Deltasul Mundo, no qual a Deltasul atua como intermediadora de uma compra entre o Cliente e o Parceiro Deltasul Mundo, o Cliente, por meio do aceite do presente Termo, outorga em caráter irrevogável e irretratável à Deltasul poderes específicos para realizar a competente operação de câmbio nos termos do art. 117 da Circular 3.691/13.</p>
                        <p style="margin: 8px 0px">9.2. A Deltasul atuará, nos termos da Resolução 3.954/11, 8º, IX e 9º, III, parágrafo único, como correspondente cambial do BEXS Banco de Câmbio S/A, CNPJ: 13.059.145/0001-00, Ouvidoria: 0800-777-2397.</p>
                        <p style="margin: 8px 0px"><b>10.</b> <b>ofertas</b></p>
                        <p style="margin: 8px 0px">10.1. As ofertas podem ser encontradas na página principal do site da Deltasul e na lista de departamentos. Porém, uma oferta pode ser retirada do site quando os Produtos em estoque estiverem esgotados e não for possível efetuar a reposição com nossos fornecedores e/ou Parceiros.</p>
                        <p style="margin: 8px 0px">10.2. O Cliente deve ler atentamente o regulamento de cada oferta antes de fechar a compra. Em caso de dúvida, o Cliente deverá entrar em contato com o nosso Setor de Atendimento ao Cliente (SAC).</p>
                        <p style="margin: 8px 0px">10.3. Nos casos de ofertas de Produtos vendidos no Marketplace ou na Deltasul Mundo, o Cliente desde já reconhece que os Parceiros são exclusivamente responsáveis por todas as informações disponibilizadas no anúncio dos Produtos, incluindo, mas não se limitando, ao título, descrição, imagens, preço, prazos de entrega.</p>
                        <p style="margin: 8px 0px"><b>11.</b> <b>produtos anunciados na Deltasul mundo</b></p>
                        <p style="margin: 8px 0px">11.1. O Cliente declara estar ciente de que algumas indicações constantes na embalagem, nos manuais e/ou no rótulo dos Produtos poderão estar em outro idioma, cabendo ao Cliente tomar todas as medidas necessárias para a exata compreensão do funcionamento ou do uso do Produto importado, sendo sua exclusiva responsabilidade verificar todos os termos das ofertas disponibilizadas pelo Parceiro Deltasul Mundo.</p>
                        <p style="margin: 8px 0px">11.2. Nas compras realizadas na Deltasul Mundo, o Cliente declara e concorda que: (i) será o importador do Produto no Brasil; (ii) o produto está sendo importado para uso próprio, sem finalidade de revenda e/ou distribuição; (iii) é exclusivamente responsável por verificar todas as condições aplicáveis ao Produto importado; (iv) assumirá a responsabilidade e os riscos por eventuais inconformidades verificadas no Produto importado; (v) realizará a importação do Produto de acordo com as leis e os regulamentos da legislação brasileira e em observância às políticas da Deltasul; (vi) assumirá a responsabilidade por todos os custos relacionados à importação, bem como por eventuais custos extraordinários em razão da importação ou de fiscalização por parte dos órgãos públicos brasileiros durante o processo de nacionalização dos Produtos; (vii) realizará todos os tipos de consultas necessárias para atestar a legalidade do Produto importado; (viii) providenciará todas as autorizações, informações e documentos necessários, conforme exigido pelos órgãos reguladores no Brasil; e (ix) tem ciência de que os prazos de entrega podem ser afetados em função do processo de importação e regularização do Produto no território nacional, conforme processos detalhados nos itens anteriores.</p>
                        <p style="margin: 8px 0px">11.3. O cliente declara ainda que o número do seu Cadastro de Pessoa Física (CPF) está válido e apto para a realização de operação cambial regulada pela legislação vigente, em especial, a Circular 3.691/2013 do Banco Central do Brasil.</p>
                        <p style="margin: 8px 0px"><b>12.</b> <b>garantia estendida</b></p>
                        <p style="margin: 8px 0px">12.1. A Garantia Estendida cobre os reparos de um Produto ou, até mesmo, a substituição do aparelho danificado por um novo, sem qualquer custo adicional para o consumidor. Trata-se de um serviço opcional para o Cliente, que pode ser adquirido no ato da compra ou em momento posterior, e entra em vigor, automaticamente, no dia seguinte ao término da garantia do fabricante. As condições gerais de uso do serviço são de responsabilidade da seguradora.</p>
                        <p style="margin: 8px 0px"><b>13.</b> <b>característica dos produtos e risco à saúde</b></p>
                        <p style="margin: 8px 0px">13.1. Antes de comprar um Produto, o Cliente deve ler atentamente em sua página a descrição do uso e manuseio, bem como a indicação de faixa etária. Em caso de dúvida, deverá contatar o Setor de Atendimento ao Cliente (SAC).</p>
                        <p style="margin: 8px 0px"><b>14.</b> <b>caso fortuito e força maior</b></p>
                        <p style="margin: 8px 0px">14.1. Nenhuma das partes será responsável perante a outra por qualquer falha ou atraso no cumprimento das obrigações constantes do presente contrato causados por casos fortuitos ou força maior.</p>
                        <p style="margin: 8px 0px"><b>15.</b> <b>foro</b></p>
                        <p style="margin: 8px 0px">15.1. Fica eleito o foro de domicílio do Cliente para dirimir eventuais controvérsias a respeito deste contrato.</p>
                        </div>
                    </div>
                  </div>
               </div>
            </div>
         </section>
    </main>
    <?php include('includes/sections/section_footer.php'); ?>
</body>
</html>