<script src="js/alpine.min.js" defer></script>
<div class="xl:flex flex-col xl:flex-row xl:w-1/6 w-full fixed xl:min-h-screen shadow-md xl:shadow-none xl:p-4 xl:z-0 z-30">
  <div @click.away="open = false" class="flex flex-col w-full text-gray-700 bg-white dark:bg-gray-700 flex-shrink-0 rounded-lg" x-data="{ open: false }">
    <div class="flex-shrink-0 px-8 py-4 flex flex-row items-center justify-between flex-wrap xl:justify-center">
      <img src="img/Logo_Deltasul_02.png" id="img_logo_header" class="h-6 sm:h-7 dark:filter" alt="Deltasul" />
      <a href="" class="hidden text-lg font-medium tracking-widest text-gray-900 uppercase rounded-lg dark:text-white focus:outline-none focus:shadow-outline">Lojas<b>Deltasul</b></a>
      <button class="rounded-lg xl:hidden focus:outline-none focus:shadow-outline dark:text-white" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <nav :class="{'block': open, 'hidden': !open}" class="flex-grow xl:block px-4 pb-4 xl:pb-0 xl:overflow-y-auto">

      <a class="flex items-center item_menu py-2 mt-4 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_index.php"><span class="material-icons mx-2 text-xl text-gray-700">dashboard</span>Dashboard</a>
      <?php if (in_array("1", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_relatorios.php"><span class="material-icons mx-2 text-xl text-gray-700">analytics</span>Relatórios</a><?php } ?>
      <?php if (in_array("2", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_produtos_no_site.php"><span class="material-icons mx-2 text-xl text-gray-700">inventory</span>Produtos no Site</a><?php } ?>
      <?php if (in_array("3", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_slider.php"><span class="material-icons mx-2 text-xl text-gray-700">slideshow</span>Slider</a><?php } ?>
      <?php if (in_array("4", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_contato_clientes.php"><span class="material-icons mx-2 text-xl text-gray-700">supervisor_account</span>Contato Clientes</a><?php } ?>
      <?php if (in_array("5", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_avaliacoes_clientes.php"><span class="material-icons mx-2 text-xl text-gray-700">record_voice_over</span>Avaliações Clientes</a><?php } ?>
      <?php if (in_array("6", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_cidades_recorrentes.php"><span class="material-icons mx-2 text-xl text-gray-700">location_city</span>Cidades Recorrentes</a><?php } ?>
      <?php if (in_array("7", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_clicks_de_interesse.php"><span class="material-icons mx-2 text-xl text-gray-700">highlight_alt</span>Clicks de Interesse</a><?php } ?>
      <?php if (in_array("8", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_inserir_ficha_tecnica.php"><span class="material-icons mx-2 text-xl text-gray-700">addchart</span>Inserir Ficha Técnica</a><?php } ?>
      <?php if (in_array("9", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_modelar_ficha_tecnica.php"><span class="material-icons mx-2 text-xl text-gray-700">data_object</span>Modelar Ficha Técnica</a><?php } ?>
      <?php if (in_array("10", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_agregar_itens.php"><span class="material-icons mx-2 text-xl text-gray-700">scatter_plot</span>Agregar Itens</a><?php } ?>
      <?php if (in_array("11", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_folheto_ofertas.php"><span class="material-icons mx-2 text-xl text-gray-700">local_offer</span>Folheto Ofertas</a><?php } ?>
      <?php if (in_array("12", $_SESSION['permissoes'])) { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_colaboradores.php"><span class="material-icons mx-2 text-xl text-gray-700">groups</span>Colaboradores</a><?php } ?>
      <?php if ($_SESSION['admin'] == 'S') { ?><a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="dashboard_liberar_acessos.php"><span class="material-icons mx-2 text-xl text-gray-700">admin_panel_settings</span>Liberar Acessos</a><?php } ?>
      <a class="flex items-center item_menu py-2 mt-2 text-gray-900 dark:text-white rounded-lg dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:focus:text-white dark:hover:text-white hover:text-gray-900 focus:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:shadow-outline" href="logout.php"><span class="material-icons mx-2 text-xl text-gray-700">logout</span>Sair</a>
              <button id="theme-toggle" type="button" class="w-full transition-all block px-4 py-2 mt-2 text-sm font-medium text-gray-900 dark:text-white bg-transparent dark:hover:bg-gray-600 dark:focus:bg-gray-600 dark:hover:text-white hover:text-gray-900 rounded-lg focus:text-gray-900 hover:bg-gray-100 focus:outline-none focus:shadow-outline">
                  <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
                  <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
              </button>
    </nav>
  </div>
</div>

<script>
    var url_base = $(location).attr('href');
    var url_geral = url_base.split("/");
    var ultimo = ((url_geral.length)-1);
    var url = url_geral[ultimo].split(".php");
    $( ".item_menu" ).each(function( index ) {
        if(this.href.includes(url[0])){
            $(this).addClass("bg-gray-100 dark:bg-gray-600");
        };
    });
</script>